baseURL = ''
languageCode = 'ru-ru'

disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

defaultContentLanguage = "ru"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

theme = "hugo-scroll"

title = "Мастер по Климату"

enableGitInfo = true

[params]
    favicon = "images/favicon.png"
    images = ["images/cover-image1.jpg"]
    title_guard = false
    title = "Мастер по Климату"
    description = "Профессиональный мастер в Москве по установке и обслуживанию кондиционеров. Более 15 лет опыта. Качественные комплектующие от проверенных поставщиков."
    hidedesignbyline = true
    invertSectionColors = true

    [params.meta]
        keywords = "кондиционер, обслуживание, заправка, установка, ремонт, москва, сплит-система, климат, кондиционер москва, обслуживание кондиционеров"
        author = "Мастер по Климату"
