[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  TZ = "UTC"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
